echo "                                                                                            "
echo "                                                                                            "
echo "                                                                                            "
echo "$_BLUE                   &&&&&&&&/&&                                                        "
echo "$_BLUE                     .&&&&&&&&*&. &&                                           $_RESET"
echo "$_BLUE                        &&&&&&&&&&&  *&%                                       $_RESET"
echo "$_BLUE                         &&&&&&&&&&&&&&&&&&&&&  &&&&/                          $_RESET"
echo "$_BLUE                        ,&&&&&&&&&&&&&&&&&&&&&&&&&&&&&* #&&#                   $_RESET"
echo "$_BLUE                     &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&(#&&              $_RESET"
echo "$_BLUE                   &&&&&&&&&&&&&&&&&&&&&&&&&&&&  &&&&&&&&&&&&&&&&&&&&          $_RESET"
echo "$_BLUE                 &&& &&&&&&&&&&  && &&& &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&       $_RESET"
echo "$_BLUE              #% &&&&&&&&&&&&   &  &&  &&&&%&&&&&&&&&&&&&&&&&&&&&&&&(         $_RESET"
echo "$_BLUE               &&&&&&&&&            &      && $_RESET    $_WHITE .,.        &&&&            $_RESET"
echo "$_BLUE              &&&, # $_RESET                                $_WHITE /&&&&&&&#                $_RESET"
echo "$_WHITE           $_BLUE &&&& $_RESET        $_WHITE (&&&&&&&&&&&&&&                                      $_RESET"
echo "$_WHITE         $_BLUE %&& $_RESET $_WHITE&&    &&  &&&&%         &&&&&&&&&&&&&                         $_RESET"
echo "$_WHITE        $_BLUE & $_RESET  $_WHITE &&& $_RESET  $_WHITE &   &&/ $_RESET                     $_BLUE /@&&&&&                     $_RESET"
echo "$_WHITE              /&&      &&, $_RESET                        $_BLUE , &&&&&,                   $_RESET"
echo "$_WHITE               & &    &&* $_RESET                            $_BLUE &&&&&                   $_RESET"
echo "$_WHITE                & *    & $_RESET           $_BLUE (&                 $_BLUE ,&&&                  $_RESET"
echo "$_WHITE                 & $_RESET   $_BLUE %& $_RESET        $_BLUE &&&                     $_BLUE &&                 $_RESET"
echo "$_BLUE                .&& $_RESET   $_BLUE &&&& $_RESET   $_BLUE &&&&                                          $_RESET"
echo "$_WHITE                $_BLUE &&&&% $_RESET $_WHITE & $_RESET   $_BLUE &&&&&                                           $_RESET"
echo "$_BLUE                 & $_RESET      $_WHITE & $_RESET $_BLUE @&&&                                             $_RESET"
echo "$_WHITE                           & $_RESET$_BLUE &&&&                                             $_RESET"
echo "                           $_BLUE &# &&&                                             $_RESET"
echo "                            $_BLUE &&                                                $_RESET"
echo "                             $_BLUE &&&*                                             $_RESET"
echo "                              $_BLUE &&&&                                            $_RESET"
echo "                               $_BLUE &&&#                                           $_RESET"
echo "                                 $_BLUE &&.                                          $_RESET"
echo "                                    $_BLUE #                                         $_RESET"
echo "                                                                                                "
echo "                                                                                                "

